name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "'auto' should be preferred in most cases, see README for details"
        required: true
        default: auto
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

jobs:
  build_release:
    name: Build & release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Need access to history for comparing previous releases
          ref: ${{ github.head_ref }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Create new version
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}
        run: |
          yarn run create-release
          echo "release_version=`git describe`" >> $GITHUB_ENV

      - name: Publish npm package
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_version }}
          release_name: Release ${{ env.release_version }}
          draft: false
          prerelease: false
          body_path: ./changes.md
